{
 "title": "Keptn Applications",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": {
     "query": "label_values(keptn_deployment_app_name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "keptn_app_count_total{keptn_deployment_app_status=\"Succeeded\", keptn_deployment_app_name=\"$Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(keptn_app_active{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "keptn_app_count_total{keptn_deployment_app_status=\"Failed\", keptn_deployment_app_name=\"$Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time between Deployments",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(keptn_deployment_app_previousversion, keptn_deployment_app_version) (keptn_app_deploymentinterval{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "{{keptn_deployment_app_previousversion}} - {{keptn_deployment_app_version}}"
    }
   ]
  },
  {
   "title": "Average Time between Deployments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(keptn_deployment_workload_previousversion) (keptn_app_deploymentinterval{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(keptn_deployment_app_version) (keptn_app_deploymentduration{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "{{keptn_workload_version}}"
    }
   ]
  },
  {
   "title": "Deployments Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max(keptn_app_active{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful promotions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(keptn_promotion_count_total{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "operation": "AppPreDeployTasks",
     "service": "lifecycle-operator",
     "tags": "keptn.deployment.app.name=$Application"
    }
   ]
  },
  {
   "title": "Active Workloads",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 20 },
   "targets": [
    {
     "expr": "keptn_deployment_deploymentduration{keptn_deployment_app_name=\"$Application\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}