apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
namespace: monitoring

generatorOptions:
  labels:
    grafana_dashboard: "1"

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/keptn-overview.json
      - dashboards/keptn-applications.json
      - dashboards/keptn-workloads.json
    options:
      disableNameSuffixHash: true

resources:
  - resources/datasources.yaml
