apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
namespace: monitoring

resources:
  - grafana-dashboard-keptn-applications.yaml
  - grafana-dashboard-keptn-overview.yaml
  - grafana-dashboard-keptn-workloads.yaml
  - ./datasources.yaml
