apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd
namespace: argocd
resources:
  - resources/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - resources/secret.yaml

patches:
  - path: patches/deployment.yaml
  - path: patches/service.yaml
  - path: patches/configmap.yaml
  - path: patches/secret.yaml
