apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: argo-cd-ingress/
    repoURL: https://github.com/Plork/argocd-keptn-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
