apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: ingress-nginx
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          hostPort:
            enabled: true
          terminationGracePeriodSeconds: 0
          service:
            type: "NodePort"
          watchIngressWithoutClass: true
          nodeSelector:
            ingress-ready: "true"
          tolerations:
          - effect: "NoSchedule"
            key: "node-role.kubernetes.io/master"
            operator: "Equal"
          - effect: "NoSchedule"
            key: "node-role.kubernetes.io/control-plane"
            operator: "Equal"
          publishService:
            enabled: false
          extraArgs:
            "enable-ssl-passthrough": ""
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
