apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.5.1
    helm:
      values: |
        grafana:
          serviceMonitor:
            enabled: true
          adminPassword: admin
          sidecar.datasources.defaultDatasourceEnabled: false
          service:
            type: NodePort
            nodePort: 31445
            targetPort: 3000
        prometheus:
          prometheusSpec:
            additionalScrapeConfigs:
              - job_name: "scrape_klt"
                scrape_interval: 5s
                static_configs:
                  - targets:
                      [
                        "lifecycle-operator-metrics-service.keptn-system.svc.cluster.local:2222",
                      ]
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
