{{ if .Capabilities.APIVersions.Has "lifecycle.keptn.sh/v1" -}}
apiVersion: lifecycle.keptn.sh/v1
kind: KeptnAppContext
metadata:
  name: {{ template "node-app.fullname" . }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ template "node-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "node-app.chart" . }}
spec:
  metadata:
    commit-id: {{ .Values.commitID }}
    environment: {{ .Values.environment }}
{{end}}
